title	"Hotel Management"
		list	p=16f84A
		radix	hex
		include	"p16f84A.inc"
		
COUNT1	EQU		D'12' ;used for delay
;COUNT2	EQU		D'13'
COUNT3	EQU		D'14' ;used for delay
COUNT	EQU		D'15' ;used for delayms
COUNT4	EQU		D'16' ;used for delay10
COUNT5	EQU		D'17' ;used for delay10
INDEX	EQU		D'18' ;bit 4 index, bit 5,6,7,0,1 for rooms 2,3,4,5,1
INDEX1	EQU		D'19' ;to know on which screen we are: bit 0 for hotels, bit 1 for chk, bit 2 for single double, bit 3 for room nb, bit 4 for day menu
;NUMBER	EQU		D'20'
INDEX2	EQU		D'21' ;save the state on each screen: 0 for hotel1 or hotel2, bit 1 for check in or check out, bit 2 for single or double
COUNT6	EQU		D'22' ;to save room nb
NUMBER1	EQU		D'34' ;teporary register
COUNT7	EQU		D'35' ;to save day nb
INDEX3	EQU		D'36' ;to know if we are on the select of day menu or room nb menu + index for the thousand $
COUNT8	EQU		D'37' ;used in the loop which sets the registers 22 to 32 to 0
COUNT9	EQU		D'38' ;used in the loop which sets the registers 22 to 32 to 0
COUNT10	EQU		D'49' ;offset
TEMP	EQU		D'50' ;temporary register
COUNT11	EQU		D'51' ;used in the simulate subroutine as a counter
COUNT12	EQU		D'52' ;used for automatic reset when on hotel 1
COUNT13	EQU		D'53' ;used for automatic reset when on hotel 1

		ORG		0x0
		GOTO	MAIN
		ORG		0x04
		BTFSC	INTCON, RBIF
		GOTO	RB4INT
		BTFSC	INTCON, T0IF
		GOTO	TMR0INT

MAIN	BSF		STATUS, RP0 ;inputs and outputs
		MOVLW	B'11110000'
		MOVWF	TRISB
		CLRF	TRISA
		MOVLW 	B'10000111'
		MOVWF	OPTION_REG
		BCF		STATUS, RP0
		BCF		INDEX, 4
		BSF		INDEX, 5
		CLRF	PORTB

		MOVLW	D'22'
		MOVWF	FSR
		MOVLW	D'0'
		MOVWF	COUNT9 ;number 0
		MOVLW	D'10'
		MOVWF	COUNT8
		;BCF		INDEX1, 0
				
LOOP11	DECFSZ	COUNT8,F ;set registers 22 to 32 to zero
		GOTO	NEXT11
		GOTO	END_FSR1
		
NEXT11	MOVF	COUNT9, 0
		MOVWF	INDF
		INCF	FSR,F
		GOTO	LOOP11

END_FSR1		MOVLW	D'38'
		MOVWF	FSR
		MOVLW	D'10'
		MOVWF	COUNT8

LOOP12	DECFSZ	COUNT8,F ;set registers 38 to 48 to zero
		GOTO	NEXT12
		GOTO	END_FSR2
		
NEXT12	MOVF	COUNT9, 0
		MOVWF	INDF
		INCF	FSR,F
		GOTO	LOOP12

END_FSR2		MOVLW	D'1'
		MOVWF	COUNT6
		MOVLW	B'00001'
		MOVWF	COUNT7
		MOVLW	D'22'
		MOVWF	FSR
		MOVLW	d'1'
		MOVWF	COUNT12
		MOVLW	d'11'
		MOVWF	COUNT13
		BCF		INDEX3, 0

INIT	CALL 	DELAY ;begin initializing the LCD
		MOVLW	B'00010'
		MOVWF	PORTA
		CALL	ET
		MOVLW	B'00010'
		MOVWF	PORTA
		CALL	ET
		MOVLW	B'01000'
		MOVWF	PORTA
		CALL	ET

		CALL	DELAY

		MOVLW	B'00000'
		MOVWF	PORTA
		CALL	ET
		MOVLW	B'01100'
		MOVWF	PORTA
		CALL	ET

		CALL	DELAY

		MOVLW	B'00000'
		MOVWF	PORTA
		CALL	ET
		MOVLW	B'00001'
		MOVWF	PORTA
		CALL	ET

		CALL	DELAY

		MOVLW	B'00000'
		MOVWF	PORTA
		CALL	ET
		MOVLW	B'00110'
		MOVWF	PORTA
		CALL	ET

		CLRF	INTCON
		BSF		INTCON, RBIE ;set interrupts enables
		BSF		INTCON, T0IE
		BSF		INTCON, GIE

WELC	CALL	SPACEC2 ;displays welcome MS screen
		CALL	HotelW
		CALL	SPACEC
		CALL	LETTERM
		CALL	LETTERS
		CALL	DELAY
		CALL	DELAY

		CALL	CLEAR ;clear display

		BSF		PORTB, 2 ;red led on
		CALL	HOT1
		CALL	INITS
		
		CALL	HOT2
		CALL	INITD

TASK3	GOTO	TASK3 ;infinite loop		

DELAYMS	MOVLW	D'250' ;delay of 1 ms for debounce
		MOVF	COUNT
LOOP2	NOP
		DECFSZ	COUNT, F
		GOTO 	LOOP2
		RETURN

RB4INT	CALL	DELAYMS ;begin of RB4 interrupt
		BTFSS	PORTB, 4
		GOTO	SELECT
		BTFSS	PORTB, 5
		GOTO	CONFIRM
		BTFSS	PORTB, 6
		GOTO	RESETT
		BTFSS	PORTB, 7
		GOTO	SIMULATE
		GOTO	ENDRB4
						
SELECT	BTFSC	INDEX1, 4 ;subroutine called when select button is pushed
		GOTO	TWO
		BTFSC	INDEX1, 2
		GOTO	TWO
		GOTO	SELECT1
		BCF		PORTB, 2
		BCF		PORTB, 3

TWO		BTFSS	INDEX, 5
		GOTO	THREE
		CALL	CURSOR2
		CALL	TWOC
		BSF		INDEX, 6
		BCF		INDEX,5
		BTFSS	INDEX3, 0
		INCF	COUNT6, F
		BTFSC	INDEX3, 0
		INCF	COUNT7, F
		GOTO	ENDRB4

THREE	BTFSS	INDEX, 6
		GOTO	FOUR
		CALL	CURSOR2
		CALL	THREEC
		BSF		INDEX, 7
		BCF		INDEX,6
		BTFSS	INDEX3, 0
		INCF	COUNT6, F
		BTFSC	INDEX3, 0
		INCF	COUNT7, F
		GOTO	ENDRB4

FOUR	BTFSS	INDEX, 7
		GOTO	FIVE
		CALL	CURSOR2
		CALL	FOURC
		BSF		INDEX, 0
		BCF		INDEX,7
		BTFSS	INDEX3, 0
		INCF	COUNT6, F
		BTFSC	INDEX3, 0
		INCF	COUNT7, F
		GOTO	ENDRB4

FIVE	BTFSS	INDEX, 0
		GOTO	ONE
		CALL	CURSOR2
		CALL	FIVEC
		BSF		INDEX, 1
		BCF		INDEX,0
		BTFSS	INDEX3, 0
		INCF	COUNT6, F
		BTFSC	INDEX3, 0
		CALL	INC
		GOTO	ENDRB4

ONE		BTFSS	INDEX, 1
		GOTO	TWO
		CALL	CURSOR2
		CALL	ONEC
		BSF		INDEX, 5
		BCF		INDEX3, 1
		BCF		INDEX,1
		BTFSS	INDEX3, 0
		CALL	SIX
		BTFSC	INDEX3, 0
		CALL	SEVEN
		GOTO	ENDRB4	

SIX		MOVLW	D'1' ;to reinitialize count6
		MOVWF	COUNT6
		RETURN

SEVEN	MOVLW	B'00001' ;to reinitialize count7
		MOVWF	COUNT7
		RETURN

INC		INCF	COUNT7, F 
		BSF		INDEX3, 1
		RETURN

				
SELECT1	BTFSC	INDEX, 4 ;goes if not on a menu that needs the 1,2,3,4,5 numbers
		GOTO	NEXT
		CALL	NEWLINE
		CALL	ARROWC
		CALL	FIRSTLINE
		CALL	SPACEC
		BSF		INDEX, 4
		BCF		PORTB, 2
		BSF		PORTB, 3			
		GOTO	ENDRB4
		
NEXT	CALL 	FIRSTLINE
		CALL	ARROWC
		CALL	NEWLINE
		CALL	SPACEC
		BSF		PORTB, 2
		BCF		PORTB, 3
		BCF		INDEX, 4
		GOTO	ENDRB4

CONFIRM	BTFSC	INDEX1, 0 ;subroutine called when psuh button is pushed
		GOTO	NEXT1
		BTFSC	INDEX, 4
		BSF		INDEX2, 0
		BTFSS	INDEX, 4
		BCF		INDEX2, 0
;		BTFSC	INDEX2, 0
;		GOTO	SIN

CHK		CALL	FIRSTLINE ;displays check in check out
		CALL	ARROWC
		CALL	LETTERC
		CALL	LETTERH
		CALL	LETTERK
		CALL	SPACEC
		CALL	LETTERI
		CALL	LETTERN
		CALL	NEWLINE
		CALL	SPACEC
		CALL	LETTERC
		CALL	LETTERH
		CALL	LETTERK
		CALL	LETTERO
		CALL	LETTERU
		CALL	LETTERT
		BSF		INDEX1, 0	
		BCF		INDEX, 4
		CALL	RED
		GOTO	ENDRB4

RED		BCF		PORTB, 3 ;turns on the red led and turn off green led
		BSF		PORTB, 2
		RETURN

;SIN		BSF		INDEX1, 0	
;		BCF		INDEX, 4
;		GOTO	CONFIRM

NEXT1	BTFSC	INDEX1, 1 ;prints single or double
		GOTO	NEXT4
		CALL	FIRSTLINE
		CALL	ARROWC
		CALL	LETTERS
		CALL	LETTERI
		CALL	LETTERN
		CALL	LETTERG
		CALL	LETTERL
		CALL	LETTERE
		CALL	NEWLINE
		CALL	SPACEC
		CALL	LETTERD
		CALL	LETTERO
		CALL	LETTERU
		CALL	LETTERB
		CALL	LETTERL
		CALL	LETTERE
		BSF		INDEX1, 1
		BTFSC	INDEX, 4
		BSF		INDEX2, 1
		BTFSS	INDEX, 4
		BCF		INDEX2, 1
		BCF		INDEX, 4
		CALL	RED
		GOTO	ENDRB4

NEXT2	BTFSC	INDEX1, 2 ;prints room number menu
		GOTO	NEXT3

		BCF		INDEX3, 0
		CALL	FIRSTLINE
		CALL	LETTERR
		CALL	LETTERO
		CALL	LETTERO
		CALL	LETTERM
		CALL	SPACEC
		CALL	LETTERN
		CALL	LETTERB
		CALL	NEWLINE
		CALL	SPACEC
		CALL	ONEC
		CALL	SPACEC2
		CALL	SPACEC

		BTFSC	INDEX2, 0
		GOTO	CONT4

		BTFSC	INDEX, 4
		BSF		INDEX2, 2
		BTFSS	INDEX, 4
		BCF		INDEX2, 2
		CALL	RED

CONT4	BSF		INDEX1, 2
		;BCF		INDEX, 4
		CLRF	INDEX
		BSF		INDEX, 5
		CALL	RED
		GOTO	ENDRB4

NEXT4	BTFSS	INDEX2, 0 ;print day menu
		GOTO	NEXT2
		BTFSC	INDEX2, 1
		GOTO	NEXT2
		BTFSC	INDEX1, 4
		GOTO	NEXT2
		CALL	FIRSTLINE
		CALL	SPACEC
		CALL	LETTERD
		CALL	LETTERA
		CALL	LETTERY
		CALL	SPACEC2
		CALL	NEWLINE
		CALL	SPACEC
		CALL	ONEC
		CALL	SPACEC2
		CALL	SPACEC
		BSF		INDEX1, 4
		BSF		INDEX3, 0

		BTFSC	INDEX, 4
		BSF		INDEX2, 2
		BTFSS	INDEX, 4
		BCF		INDEX2, 2

		BCF		INDEX, 4
		CALL	RED
		GOTO	ENDRB4

NEXT3	BTFSC	INDEX1, 5 
		GOTO	LAST

		BTFSC	INDEX1, 3
		GOTO	RETRY
		BTFSC	INDEX2, 1
		GOTO	CONT
		
CONT	BTFSS	INDEX2, 2 ;choose which fsr according to single or double
		CALL	FSRSINGLE
		BTFSC	INDEX2, 2
		CALL	FSRDOUBLE

		BTFSS	INDEX2, 1
		GOTO	IN
		BTFSC	INDEX2, 1
		GOTO	OUT

FSRSINGLE
		MOVF	COUNT6, 0
		ADDLW	D'22'
		MOVWF	FSR
		RETURN

FSRDOUBLE
		MOVF	COUNT6, 0
		ADDLW	D'27'
		MOVWF	FSR
		RETURN
		
IN		BTFSS	INDEX2, 2 ;subroutine if check in
		GOTO	SINGLEIN
		BTFSC	INDEX2, 2
		GOTO 	DOUBLEIN

OUT		BTFSS	INDEX2, 2 ;subroutine if check out
		GOTO	SINGLEOUT
		BTFSC	INDEX2, 2
		GOTO 	DOUBLEOUT

LAST	GOTO	RETRY


SINGLEIN ;if single + check in
		BTFSC	INDF, 0
		GOTO	ERRORR
		CALL	LINE1
		MOVLW	H'A'
		ADDWF	COUNT6, 0
		MOVWF	PORTA
		CALL	ET
		CALL	HASHC
		CALL	BILL

		BSF		NUMBER1, 0
		MOVF	NUMBER1, 0
		MOVWF	INDF

		MOVF	COUNT6, 0
		ADDLW	D'38'
		MOVWF	FSR
		MOVF	COUNT7, 0
		MOVWF	INDF
		
		BSF		INDEX1, 5
		GOTO	ENDRB4
						

DOUBLEIN ;if double + check in
		BTFSC	INDF, 0
		GOTO	ERRORR
		CALL	LINE2
		MOVLW	H'A'
		ADDWF	COUNT6, 0
		MOVWF	PORTA
		CALL	ET
		CALL	HASHC
		CALL	BILL

		BSF		NUMBER1, 0
		MOVF	NUMBER1, 0
		MOVWF	INDF

		MOVF	COUNT6, 0
		ADDLW	D'43'
		MOVWF	FSR
		MOVF	COUNT7, 0
		MOVWF	INDF

		BSF		INDEX1, 5
		GOTO	ENDRB4
		

SINGLEOUT ;if single + check out
		BTFSS	INDF, 0
		GOTO	ERRORR
		CALL	LINE1
		MOVLW	H'A'
		ADDWF	COUNT6, 0
		MOVWF	PORTA
		CALL	ET
		CALL	STARC
		CALL	SUCC

		BCF		NUMBER1, 0
		MOVF	NUMBER1, 0
		MOVWF	INDF

		GOTO	RETRY

DOUBLEOUT ;if double + check out
		BTFSS	INDF, 0
		GOTO	ERRORR
		CALL	LINE2
		MOVLW	H'A'
		ADDWF	COUNT6, 0
		MOVWF	PORTA
		CALL	ET
		CALL	STARC
		CALL	SUCC

		BCF		NUMBER1, 0
		MOVF	NUMBER1, 0
		MOVWF	INDF

		GOTO	RETRY

ERRORR	BSF		PORTB, 0 ;buzzer sound and led red
		BCF		PORTB, 3
		BSF		PORTB, 2
		CALL	DELAY
		CALL	DELAY
		BCF		PORTB, 0
						
RETRY	CALL	RESET1 ;resets indeces
		;BTFSS	INDEX2, 0
		GOTO	CHK
		;BTFSC	INDEX2, 0
		;GOTO	SIN

ENDRB4	BCF		INTCON, RBIF ;end interrupt RB4
		RETFIE

BILL	CALL	FIRSTLINE ;function that prints bill
		CALL	SPACEC
		CALL	LETTERB
		CALL	LETTERI
		CALL	LETTERL
		CALL	LETTERL
		CALL	SPACEC
		CALL	SPACEC
		CALL	NEWLINE
		CALL	SPACEC
		CALL	DOLLARC
		BTFSC	INDEX2, 0 ;go if hotel 2
		GOTO	BILL2
		BTFSC	INDEX2, 2
		CALL	TWOC
		BTFSS	INDEX2, 2		
		CALL	ONEC
CONT1	CALL	ZEROC
		CALL	ZEROC
		CALL	SPACEC
CONT2	CALL	SPACEC
		CALL	SUCC
		RETURN

BILL2	MOVLW	B'10011'
		MOVWF	PORTA
		CALL	ET
		BTFSC	INDEX2, 2
		GOTO	BILLNEXT ;go if double room
		MOVF	COUNT7, W
		ADDLW	B'10000'
		MOVWF	PORTA
		CALL	ET
		GOTO	CONT1 

BILLNEXT
		BTFSC	INDEX3, 1
		GOTO	THOU
		MOVF	COUNT7, W
		ADDWF	COUNT7, W
		ADDLW	B'10000'
		MOVWF	PORTA
		CALL	ET
		GOTO	CONT1

THOU	CALL	HALFONEC
		CALL	ZEROC
		CALL	ZEROC
		CALL	ZEROC
		GOTO	CONT2		

SUCC	BCF		PORTB, 2 ;turns on green led and turns off red led
		BSF		PORTB, 3
		CALL	DELAY
		RETURN

RESET1	BCF		INDEX1, 1 ;reset indices
		BCF		INDEX1, 2
		BCF		INDEX1, 3
		BCF		INDEX1, 4
		BCF		INDEX1, 5
		BCF		INDEX2, 1
		BCF		INDEX2, 2
		CLRF	INDEX
		CLRF	INDEX3
		BSF		INDEX, 5
		MOVLW	D'1'
		MOVWF	COUNT6
		MOVLW	B'00001'
		MOVWF	COUNT7
		MOVLW	D'22'
		MOVWF	FSR
		BSF		PORTB, 2
		BCF		PORTB, 3
		RETURN

RESETT	CALL	RESET2 ;subroutine called when reset button is pushed
		CALL	FIRSTLINE
		CALL	HOT1
		CALL	HOT2
		BCF		INDEX2, 0
	;	CALL	DELAY
	;	CALL	DELAY
		GOTO	ENDRB4
		GOTO	TASK3

RESET2	MOVLW	D'22'
		MOVWF	FSR
		MOVLW	D'0'
		MOVWF	COUNT9 ;number 0
		MOVLW	D'10'
		MOVWF	COUNT8
		BCF		INDEX1, 0

				
LOOP7	DECFSZ	COUNT8,F ;set registers 22 to 32 to zero
		GOTO	NEXT7
		GOTO	END_FSR
		
NEXT7	MOVF	COUNT9, 0
		MOVWF	INDF
		INCF	FSR,F
		GOTO	LOOP7

		MOVLW	D'38'
		MOVWF	FSR
		MOVLW	D'10'
		MOVWF	COUNT8

LOOP8	DECFSZ	COUNT8,F ;set registers 38 to 48 to zero
		GOTO	NEXT8
		GOTO	END_FSR
		
NEXT8	MOVF	COUNT9, 0
		MOVWF	INDF
		INCF	FSR,F
		GOTO	LOOP8

END_FSR	CALL	RESET1 ;prints reset done
		CALL	FIRSTLINE
		CALL	SPACEC
		CALL	LETTERR
		CALL	LETTERE
		CALL	LETTERS
		CALL	LETTERE
		CALL	LETTERT
		CALL	SPACEC
		CALL	SPACEC
		CALL	INITS
		CALL	NEWLINE
		CALL	SPACEC
		CALL	LETTERD
		CALL	LETTERO
		CALL	LETTERN
		CALL	LETTERE
		CALL	SPACEC
		CALL	SPACEC
		CALL	SPACEC
		CALL	INITD
		CALL	DELAY
		;INCF	COUNT6, 1
		RETURN

SIMULATE ;subroutine called when simulate push button is pushed
		BTFSS	INDEX2, 0
		GOTO	ENDRB4

		MOVLW	D'23'
		MOVWF	FSR
		MOVLW	D'9'
		MOVWF	COUNT8
		MOVLW	D'4'
		MOVWF	COUNT11

LOOP9	MOVF	FSR, W ;checks which rooms are full
		MOVWF	TEMP ;save FSR in temp
		DECFSZ	COUNT11, F
		GOTO	CONT6
		BSF		INDEX3, 2 ;now double rooms

CONT6	DECFSZ	COUNT8,F
		GOTO	DECR
		GOTO	PASSED
		
;NEXT9	BTFSC	INDF, 0
;		GOTO	DECR
;		INCF	FSR,F
;		GOTO	LOOP9

DECR	MOVLW	D'22' ;decrement for number of days
		SUBWF	FSR, W
		MOVWF	COUNT10 ;saved offset
		MOVLW	D'38'
		ADDWF	COUNT10, W
		MOVWF	FSR

		DECFSZ	INDF, F
		GOTO	AGAIN
		GOTO	UPDATE	

UPDATE	BTFSS	INDEX3, 2 ;it chooses if it will decrement for single or double room
		CALL	UPDATES
		BTFSC	INDEX3, 2
		CALL	UPDATED
		GOTO	FINISH

UPDATES	CALL	LINE1 
		MOVLW	H'A'
		ADDWF	COUNT10, W
		MOVWF	PORTA
		CALL	ET
		CALL	STARC
		RETURN

UPDATED	CALL	LINE2
		MOVLW	H'5'
		ADDWF	COUNT10, W
		MOVWF	PORTA
		CALL	ET
		CALL	STARC
		RETURN
		
FINISH	MOVF	TEMP, W
		MOVWF	FSR
		ADDWF	COUNT10, W

		MOVWF	FSR
		BCF		INDF, 0

AGAIN	MOVF	TEMP, W
		MOVWF	FSR

		INCF	FSR,F
		GOTO	LOOP9

PASSED	CALL	FIRSTLINE ;prints day passed
		CALL	SPACEC
		CALL	LETTERD
		CALL	LETTERA
		CALL	LETTERY
		CALL	SPACEC2
		CALL	NEWLINE
		CALL	SPACEC
		CALL	LETTERP
		CALL	LETTERA
		CALL	LETTERS
		CALL	LETTERS
		CALL	LETTERE
		CALL	LETTERD
		CALL	DELAY
		CALL	DELAY
		CALL	RESET1
		GOTO	CHK
		

TMR0INT	BTFSC	INDEX2 ,0 ;begin of TMR0 interrupt
		GOTO	RETZ		
		DECFSZ	COUNT12,F
		GOTO	RETZ
		DECFSZ	COUNT13,F
		GOTO	RETZ
		CALL	RESET2
		CALL	RESET1	
		CLRF	TMR0
		MOVLW	d'255'
		MOVWF	COUNT12
		MOVLW	d'11'
		MOVWF	COUNT13
		BSF		PORTB, 0
		CALL	DELAY
		CALL	DELAY
		BCF		PORTB, 0
		GOTO	CHK
		
RETZ	BCF		INTCON,	T0IF ;end of TMR0 interrupt
		RETFIE
		
ET		BSF		PORTB,1
		NOP
		BCF		PORTB,1
		CALL	DELAY10
		RETURN
		
DELAY	MOVLW	D'255'
		MOVWF	COUNT1
		MOVLW 	D'53'
		MOVWF	COUNT3
	
LOOP	INCFSZ	COUNT1, F
		GOTO	LOOP
		DECFSZ	COUNT3, F
		GOTO	LOOP
		RETURN

DELAY10	MOVLW	D'255'
		MOVWF	COUNT4
		MOVLW 	D'12'
		MOVWF	COUNT5
	
LOOP1	INCFSZ	COUNT4, F
		GOTO	LOOP1
		DECFSZ	COUNT5, F
		GOTO	LOOP1
		RETURN

HotelW	MOVLW	B'10100' ;H letter
		MOVWF	PORTA
		CALL	ET
		MOVLW	B'11000'
		MOVWF	PORTA
		CALL	ET

		MOVLW	B'10100' ;O letter
		MOVWF	PORTA
		CALL	ET
		MOVLW	B'11111'
		MOVWF	PORTA
		CALL	ET

		MOVLW	B'10101' ;T letter
		MOVWF	PORTA
		CALL	ET
		MOVLW	B'10100'
		MOVWF	PORTA
		CALL	ET

		MOVLW	B'10100' ;E letter
		MOVWF	PORTA
		CALL	ET
		MOVLW	B'10101'
		MOVWF	PORTA
		CALL	ET

		MOVLW	B'10100' ;L letter
		MOVWF	PORTA
		CALL	ET
		MOVLW	B'11100'
		MOVWF	PORTA
		CALL	ET
		RETURN

LETTERM	MOVLW	B'10100'
		MOVWF	PORTA
		CALL	ET
		MOVLW	B'11101'
		MOVWF	PORTA
		CALL	ET
		RETURN

LETTERP	MOVLW	B'10101'
		MOVWF	PORTA
		CALL	ET
		MOVLW	B'10000'
		MOVWF	PORTA
		CALL	ET
		RETURN

LETTERS	MOVLW	B'10101'
		MOVWF	PORTA
		CALL	ET
		MOVLW	B'10011'
		MOVWF	PORTA
		CALL	ET
		RETURN

LETTERD	MOVLW	B'10100'
		MOVWF	PORTA
		CALL	ET
		MOVLW	B'10100'
		MOVWF	PORTA
		CALL	ET
		RETURN

LETTERC	MOVLW	B'10100'
		MOVWF	PORTA
		CALL	ET
		MOVLW	B'10011'
		MOVWF	PORTA
		CALL	ET
		RETURN

LETTERH	MOVLW	B'10100'
		MOVWF	PORTA
		CALL	ET
		MOVLW	B'11000'
		MOVWF	PORTA
		CALL	ET
		RETURN

LETTERK	MOVLW	B'10100'
		MOVWF	PORTA
		CALL	ET
		MOVLW	B'11011'
		MOVWF	PORTA
		CALL	ET
		RETURN

LETTERI	MOVLW	B'10100'
		MOVWF	PORTA
		CALL	ET
		MOVLW	B'11001'
		MOVWF	PORTA
		CALL	ET
		RETURN

LETTERN	MOVLW	B'10100'
		MOVWF	PORTA
		CALL	ET
		MOVLW	B'11110'
		MOVWF	PORTA
		CALL	ET
		RETURN

LETTERO	MOVLW	B'10100'
		MOVWF	PORTA
		CALL	ET
		MOVLW	B'11111'
		MOVWF	PORTA
		CALL	ET
		RETURN

LETTERU	MOVLW	B'10101'
		MOVWF	PORTA
		CALL	ET
		MOVLW	B'10101'
		MOVWF	PORTA
		CALL	ET
		RETURN

LETTERT	MOVLW	B'10101'
		MOVWF	PORTA
		CALL	ET
		MOVLW	B'10100'
		MOVWF	PORTA
		CALL	ET
		RETURN

LETTERG	MOVLW	B'10100'
		MOVWF	PORTA
		CALL	ET
		MOVLW	B'10111'
		MOVWF	PORTA
		CALL	ET
		RETURN

LETTERL	MOVLW	B'10100'
		MOVWF	PORTA
		CALL	ET
		MOVLW	B'11100'
		MOVWF	PORTA
		CALL	ET
		RETURN

LETTERE	MOVLW	B'10100'
		MOVWF	PORTA
		CALL	ET
		MOVLW	B'10101'
		MOVWF	PORTA
		CALL	ET
		RETURN

LETTERR	MOVLW	B'10101'
		MOVWF	PORTA
		CALL	ET
		MOVLW	B'10010'
		MOVWF	PORTA
		CALL	ET
		RETURN

LETTERA	MOVLW	B'10100'
		MOVWF	PORTA
		CALL	ET
		MOVLW	B'10001'
		MOVWF	PORTA
		CALL	ET
		RETURN

LETTERY	MOVLW	B'10101'
		MOVWF	PORTA
		CALL	ET
		MOVLW	B'11001'
		MOVWF	PORTA
		CALL	ET
		RETURN

LETTERB	MOVLW	B'10100'
		MOVWF	PORTA
		CALL	ET
		MOVLW	B'10010'
		MOVWF	PORTA
		CALL	ET
		RETURN

STARC	MOVLW	B'10010' ;prints star
		MOVWF	PORTA
		CALL	ET
		MOVLW	B'11010'
		MOVWF	PORTA
		CALL	ET
		RETURN

HASHC	MOVLW	B'10010' ;prints hash
		MOVWF	PORTA
		CALL	ET
		MOVLW	B'10011'
		MOVWF	PORTA
		CALL	ET
		RETURN

ARROWC	MOVLW	B'10011' ;prints arrow
		MOVWF	PORTA
		CALL	ET
		MOVLW	B'11110'
		MOVWF	PORTA
		CALL	ET
		RETURN

SPACEC	MOVLW	B'10010' ;prints space
		MOVWF	PORTA
		CALL	ET
		MOVLW	B'10000'
		MOVWF	PORTA
		CALL	ET
		RETURN

ONEC	MOVLW	B'10011' ;prints 1
		MOVWF	PORTA
		CALL	ET
HALFONEC		MOVLW	B'10001'
		MOVWF	PORTA
		CALL	ET
		RETURN

TWOC	MOVLW	B'10011' ;prints 2
		MOVWF	PORTA
		CALL	ET
		MOVLW	B'10010'
		MOVWF	PORTA
		CALL	ET
		RETURN

THREEC	MOVLW	B'10011' ;prints 3
		MOVWF	PORTA
		CALL	ET
		MOVLW	B'10011'
		MOVWF	PORTA
		CALL	ET
		RETURN

FOURC	MOVLW	B'10011' ;prints 4
		MOVWF	PORTA
		CALL	ET
		MOVLW	B'10100'
		MOVWF	PORTA
		CALL	ET
		RETURN

FIVEC	MOVLW	B'10011' ;prints 5
		MOVWF	PORTA
		CALL	ET
		MOVLW	B'10101'
		MOVWF	PORTA
		CALL	ET
		RETURN

DOLLARC	MOVLW	B'10010'
		MOVWF	PORTA
		CALL	ET
		MOVLW	B'10100'
		MOVWF	PORTA
		CALL	ET
		RETURN

ZEROC	MOVLW	B'10011' ;prints 0
		MOVWF	PORTA
		CALL	ET
		MOVLW	B'10000'
		MOVWF	PORTA
		CALL	ET
		RETURN	

CLEAR	MOVLW	B'00000' ;clear display
		MOVWF	PORTA
		CALL	ET
		MOVLW	B'00001'
		MOVWF	PORTA
		CALL	ET
		RETURN

NEWLINE	MOVLW	B'01100'
		MOVWF	PORTA
		CALL	ET
		MOVLW	B'00000'
		MOVWF	PORTA
		CALL	ET
		RETURN

CURSOR2	MOVLW	B'01100'
		MOVWF	PORTA
		CALL	ET
		MOVLW	B'00001'
		MOVWF	PORTA
		CALL	ET
		RETURN

FIRSTLINE		MOVLW	B'01000'
		MOVWF	PORTA
		CALL	ET
		MOVLW	B'00000'
		MOVWF	PORTA
		CALL	ET
		RETURN

LINE1	MOVLW	B'01000'
		MOVWF	PORTA
		CALL	ET
		RETURN

LINE2	MOVLW	B'01100'
		MOVWF	PORTA
		CALL	ET
		RETURN

SPACEC2	CALL	SPACEC
		CALL	SPACEC
		CALL	SPACEC
		CALL	SPACEC
		RETURN

INITS	CALL	SPACEC
		CALL	SPACEC
		CALL	LETTERS
		CALL	STARC
		CALL	STARC
		CALL	STARC
		CALL	STARC
		CALL	STARC
		RETURN

INITD	CALL	SPACEC
		CALL	SPACEC
		CALL	LETTERD
		CALL	STARC
		CALL	STARC
		CALL	STARC
		CALL	STARC
		CALL	STARC
		RETURN

HOT1	CALL	ARROWC ;prints first line
		CALL	HotelW
		CALL	ONEC
		CALL	SPACEC
		RETURN
		
HOT2	CALL	NEWLINE ;prints second line
		CALL	SPACEC
		CALL	HotelW
		CALL	TWOC
		CALL	SPACEC
		RETURN

		END